Fix issue5 : incorrect background pixmap rendering
sysprog21/mado pull request #10
Opened 2024-07-18 06:59 UTC by marvin0102

Fix the incorrect rendering of PNG files and pass the test of PNG color formats include RGB, RGBA, PALETTE and GRAY.

2024-07-18 07:02 UTC, jserv requested changes
Run `clang-format -i src/*.[ch]` and squash the git commits.

2024-07-18 07:42 UTC, jserv requested changes
You should fetch the latest `main` branch and run `git rebase -i`. See https://verdantfox.com/blog/how-to-git-rebase-mainmaster-onto-your-feature-branch-even-with-merge-conflicts

2024-07-18 07:44 UTC, jserv commented on src/image-png.c
> +#include <stdio.h>
Avoid unnecessary header inclusion.

2024-07-18 08:14 UTC, jserv requested changes
Read https://cbea.ms/git-commit/ carefully and refine your git commit messages accordingly.

2024-07-18 09:16 UTC, jserv commented
@marvin0102, You are still failing to use `git rebase` properly.

Here are the steps you can follow:
```shell
$ git remote add upstream https://github.com/sysprog21/mado
$ git fetch upstream
$ git rebase upstream/main 
```

Then, check the order of commits by running `git log -n 2`
```
commit 59a1a07e866fcffff89b9fdfb27ed14f3349676a (HEAD -> main)
Author: marvin <marvin890102@gmail.com>
Date:   Thu Jul 18 10:55:30 2024 +0800

    Fix the incorrect rendering of PNG file
    
    The RGB color formats of libpng and TWIN are inconsistent.
    The RGB format in libpng is shown as BGR format in TWIN. Add the
    transform function '_convertBGRtoARGB' to correct it.

commit b0a8bf0ff9c4307a1a8930d0f8c6236c571b33e1 (upstream/main)
Author: Jim Huang <jserv.tw@gmail.com>
Date:   Thu Jul 18 14:27:19 2024 +0800

    Simplify the build procedure
    
    Only object files should be tracked in advance, and all C source files
    can be detected via the build targets.
```

Your commit is now appearing after commit b0a8bf0ff9c4307a1a8930d0f8c6236c571b33e1, which is the latest HEAD of `main` branch.

2024-07-18 09:47 UTC, jserv commented
Tested on Ubuntu Linux 20.04:

<img width="1125" alt="comparison" src="https://github.com/user-attachments/assets/f22e18a2-4f9b-455d-87fc-a8fd93dd4d71">

TWIN attempted to render the scaled `assets/tux.png` (left), while the same PNG file is rendered by the ImageMagick tool (right). The color was incorrect though.

2024-07-19 01:14 UTC, marvin0102 commented
linux seems not to have the problem of RGB invert. I don't have a linux device nearby. Can you please test for me?

2024-07-19 01:27 UTC, jserv commented on src/image-png.c
> +#if __APPLE__
Replace with `#if defined(__APPLE__)`.

2024-07-19 03:01 UTC, jserv commented
> linux seems not to have the problem of RGB invert. I don't have a linux device nearby. Can you please test for me?

The background rendering works on Ubuntu Linux now.
<img width="641" alt="twin-sdl-linux" src="https://github.com/user-attachments/assets/f55e0957-67a1-4ab4-9210-d5ee1270f296">

2024-07-19 03:10 UTC, jserv commented
> linux seems not to have the problem of RGB invert. I don't have a linux device nearby.

Can you try various PNG files as well? Once we verify, the proposed changes can be checked in.

2024-07-19 03:29 UTC, marvin0102 commented
I already test PNG files with different color formats include RGBA, PALETTE, GRAY. The screenshots are the results of mado and the original PNG files rendered by mac Preview.
<img width="1170" alt="截圖 2024-07-19 上午11 19 17" src="https://github.com/user-attachments/assets/4c4dea5c-e9cb-4523-bff5-fdfe3b414146">
<img width="824" alt="截圖 2024-07-19 上午11 20 09" src="https://github.com/user-attachments/assets/3687a9bb-c86e-4942-86ca-9be039ad8701">
<img width="929" alt="截圖 2024-07-19 上午11 21 57" src="https://github.com/user-attachments/assets/4aa0a77d-301f-425d-9e93-043f6eed6644">
<img width="822" alt="截圖 2024-07-19 上午11 22 50" src="https://github.com/user-attachments/assets/6ac958d6-a895-49af-9ec8-1b46c20db8d3">

2024-07-19 03:33 UTC, merged

2024-07-19 03:33 UTC, jserv commented
Thank @marvin0102 for contributing!