Add macro of multiply and divide for fixed-point
sysprog21/mado pull request #45
Opened 2024-09-07 21:49 UTC by weihsinyeh

Add the helper macro for type conversion from `twin_dfixed_t` to `twin_sfixed_t`. Add the helper macro for multiplication and division, where both operands and the result are of type `twin_dfixed_t` or `twin_sfixed_t`.

2024-09-07 22:14 UTC, jserv requested changes
Avoid using [backticks](https://en.wikipedia.org/wiki/Backtick) in git commit messages and comments to ensure compatibility with terminal emulators that may not render the backtick character properly.

Instead, use the pair `'` or `"` (quotation marks).

2024-09-08 14:58 UTC, jserv requested changes
Refine the subject.

2024-09-09 20:08 UTC, jouae commented
@weihsinyeh Hey, thanks for your contribution.

You can describe how the marcos work by an example to explain why use the shift operator.

For example,
```c
/* Let two twin_sfixed_t data be a = 5, b = 4 and
 * exact a is 5/2^4 = 0.3125
 * exact b is 4/2^4 = 0.1875
 * 
 * The value of a/b is 1
 * The value of twin_sfixed_div(a, b) is 20. 
 * The exact value is 20/2^4 = 1.25 
 *
 * For floating points representation, 
 * the reslut is 0.3125/0.1875 = 1.66666666667
 */
```

If the precision and errors in fixed-point arithmetic can be expressed using mathematical language, it would be ideal. This could serve as another RP.

This reference might be helpful, Fixed-Point Arithmetic: An Introduction by Randy Yates. It gave an easy and short Introduction for the numerical range of fixed-point arithmetic in section 5.

Refs:

1. [Digital Signal Labs, Fixed-Point Arithmetic: An Introduction by Randy Yates, 2007](https://courses.cs.washington.edu/courses/cse467/08au/labs/l5/fp.pdf)
2. ISO/IEC TR 18037

2024-09-10 15:52 UTC, jouae approved these changes

2024-09-11 00:40 UTC, merged

2024-09-11 00:41 UTC, jserv commented
Thank @weihsinyeh for contributing!