Port font editor to SDL2
sysprog21/mado pull request #52
Opened 2024-09-20 21:31 UTC by jouae

Replace X11 with SDL2 to improve the portability and cross-platform support

Migrated window creation from X11's `XCreateWindow` to `SDL_CreateWindow`.

Replaced X11 event handling with SDL2’s event loop (`SDL_PollEvent`) to capture input events such as keyboard and mouse interactions.

Updated rendering to use `SDL_Renderer` and `SDL_Surface`, replacing X11's rendering functions.

* Modified some key event logic:
1. SDLK_ESCAPE: ESC now exits the program.
2. SDL_QUIT: Clicking the "X" on the window exits the program.

* Unchanged key event logic:
1. SDLK_q: Switches to the next font.

* Features not fully implemented yet:
1. SDLK_s, SDLK_u, SDLK_f, SDLK_d, SDLK_DOWN: Handling logic for stripe drawing operations.
2. SDL_WINDOWEVENT, SDL_MOUSEBUTTONDOWN.

2024-09-21 05:48 UTC, jserv commented on tools/font-edit/twin-fedit.c
> +static int exit_window = 0;
Use `bool` when possible.

2024-09-21 05:49 UTC, jserv commented on tools/font-edit/twin-fedit.c
>  static int init(int argc, char **argv)
Use `bool` as the return type.

2024-09-21 05:50 UTC, jserv commented on tools/font-edit/twin-fedit.c
> +    int quit_state = 0;
Can you eliminate the use of `quit_state`?

2024-09-21 05:51 UTC, jserv commented on tools/font-edit/twin-fedit.c
> +                break;
Why another `break`?

2024-09-21 05:52 UTC, jserv commented on tools/font-edit/twin-fedit.h
> +#include <SDL2/SDL.h>
Only include the headers you need. Minimize the header inclusions in header files.

2024-09-21 05:53 UTC, jserv commented on tools/font-edit/twin-fedit.c
> +    window = SDL_CreateWindow("Twin Fedit", SDL_WINDOWPOS_CENTERED,
Change the caption to "Font editor."

2024-09-21 05:56 UTC, jserv requested changes
Append `Close #7` at the end of git  commit messages.

2024-09-21 06:01 UTC, jserv commented
> SDLK_q: Switches to the next font.
> Features not fully implemented yet:

This functionality needs to be fully implemented, as the current font editing (which is more of a viewer at the moment) is not intuitive. By switching from reading characters from stdin to retrieving content from an open file, we can enable the ability to browse font glyphs back and forth.

2024-09-21 06:07 UTC, jserv commented on tools/font-edit/Makefile
> +CFLAGS = $(shell pkg-config --cflags cairo) $(shell sdl2-config --cflags) -g -Wall
No trailing spaces.

2024-09-21 06:09 UTC, jserv commented on tools/font-edit/twin-fedit.c
> +                    /* Press "q" key to exit play()
You don't have to mention "Press q key".

2024-09-21 06:09 UTC, jserv commented on tools/font-edit/twin-fedit.c
> +                    c);  // Ensure the content is redrawn after every key press
Always use C-style comments.

2024-09-21 18:24 UTC, weihsinyeh commented on tools/font-edit/twin-fedit.c
>                          delete (c, c->first);
delete(c, c->first);

2024-09-21 18:34 UTC, weihsinyeh commented on tools/font-edit/twin-fedit.c
> +                SDL_Keycode key_event = event.key.keysym.sym;
This issue occurs when running the make command.
```
twin-fedit.c: In function ‘play’:
twin-fedit.c:519:17: error: a label can only be part of a statement and a declaration is not a statement
  519 |                 SDL_Keycode key_event = event.key.keysym.sym;
      |                 ^~~~~~~~~~~
make: *** [<builtin>: twin-fedit.o] Error 1
```

2024-09-21 18:34 UTC, weihsinyeh commented on tools/font-edit/twin-fedit.c
> +                    /* Press "q" key to exit play()
These instructions can be added to the README.md.

2024-09-21 18:47 UTC, weihsinyeh commented on tools/font-edit/twin-fedit.c
> +        // Ensure the window surface is updated
/* Ensure the window surface is updated. */

2024-09-22 05:07 UTC, jserv commented on tools/font-edit/twin-fedit.c
> +        printf("SDL could not initialize! SDL_Error: %s\n", SDL_GetError());
Use `SDL_LogCritical` or `SDL_LogError` instead.

2024-09-23 07:05 UTC, jserv commented
For future contributions, consider the following workflow:
1. Create a new feature branch (e.g., `font-editor`) for your proposed changes instead of working directly on the `main` branch.
2. Keep your `main` branch untouched and up-to-date with the original repository. You can easily sync it using GitHub's web interface.
3. Develop and commit your changes in the feature branch.
4. When ready, create a pull request from your feature branch to the main repository.

This approach offers several benefits:
- It keeps the `main` branch clean and aligned with the upstream repository.
- It isolates feature development, making it easier to manage and review changes.
- It allows for easier collaboration and parallel development of multiple features.

See https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

2024-09-24 09:51 UTC, closed without merging

2024-10-03 03:53 UTC, jserv commented
> As suggestion above, I am closing this PR to maintain a clean and organized workflow, and I will open another PR later, which will address the issues mentioned in the above review.

You don't need to resolve all the concerns before submitting a new issue. Instead, submit an issue early to highlight your initial efforts, similar to how a draft pull request works. For the sake of collaboration, more code reviews and discussions will undoubtedly improve the overall outcome.