Fix the heap-use-after-free and memory leak
sysprog21/mado pull request #54
Opened 2024-10-01 17:53 UTC by weihsinyeh

To fix the heap-use-after-free issue when `screen` is accessed by the `twin_sdl_work()` function, remove the `_twin_sdl_destroy(screen, tx)` operation. Additionally, to address the memory leak, add the `twin_path_destroy(path)` function to ensure the unused path is properly destroyed.

Close sysprog21#49

2024-10-01 18:05 UTC, weihsinyeh commented
However, if this is the solution, the `_twin_sdl_destroy()` function will no longer be used.

2024-10-01 23:48 UTC, jserv commented
> However, if this is the solution, the `_twin_sdl_destroy()` function will no longer be used.

Quote from SDL manual about [SDL_Quit](https://wiki.libsdl.org/SDL2/SDL_Quit)
> You should call this function even if you have already shutdown each initialized subsystem with [SDL_QuitSubSystem](https://wiki.libsdl.org/SDL2/SDL_QuitSubSystem)(). It is safe to call this function even in the case of errors in initialization.
> ... You can use this function with `atexit()` to ensure that it is run when your application is shutdown, but it is not wise to do this from a library or other dynamically loaded code.

Since checking for events is no longer allowed after invoking `SDL_Quit`(), we need to find a way to properly deallocate SDL-specific resources.

2024-10-02 04:06 UTC, weihsinyeh commented
AddressSanitizer reports:
```
==12685==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 17 byte(s) in 1 object(s) allocated from:
    #0 0x55ddca5715b8 in __interceptor_malloc (/home/weihsin/linux2024/tmp/mado/demo-sdl+0xf95b8)
    #1 0x7fd3bf6a5896 in _XlcDefaultMapModifiers (/lib/x86_64-linux-gnu/libX11.so.6+0x5b896)

SUMMARY: AddressSanitizer: 17 byte(s) leaked in 1 allocation(s).
```

2024-10-02 05:44 UTC, jserv requested changes
Avoid using [backticks](https://en.wikipedia.org/wiki/Backtick) in git commit messages and comments to ensure compatibility with terminal emulators that may not render the backtick character properly.

Instead, use the pair ' or " (quotation marks).

2024-10-02 07:57 UTC, jserv requested changes
Append `Close #49` at the end of git commit message since this pull request does resolve the issue.

2024-10-02 08:32 UTC, merged

2024-10-02 08:32 UTC, jserv commented
Thank @weihsinyeh for contributing!