Add the Gaussian function to blur a pixmap
sysprog21/mado pull request #58
Opened 2024-10-06 15:49 UTC by weihsinyeh

Use Pascal's Triangle to approximate a 5x5 Gaussian Kernel, and apply Gaussian blur on the 'twin_pixmap_t' to implement the blurring technique.

See: sysprog21#34

2024-10-06 21:39 UTC, jserv commented
- [ ] The original

<img width="640" alt="the original" src="https://github.com/user-attachments/assets/c3faba5d-1cc4-4909-af3d-eac3d1b95b97">

- [ ] The proposed change

<img width="640" alt="the proposed change" src="https://github.com/user-attachments/assets/76cefdfd-c29e-42f5-ba58-699af9c50518">

The idea behind Issue #34 is to implement drop shadow, one of the most popular visual effects in modern window systems and compositing window managers. The effect should be applied at the window management level, not to background images, meaning the background image should not be blurred. The graphical effect of a visually elevated shape with a shadow underneath the window frame should occur transparently.

2024-10-06 21:40 UTC, jserv commented on include/twin.h
> +void twin_gaussian_blur(twin_pixmap_t *px);
I am not sure if it is worth to declare a public function for such purpose.

2024-10-06 21:41 UTC, jserv commented on src/draw.c
> +    uint8_t kernel[5][5] = {{0x01, 0x04, 0x06, 0x04, 0x01},
You should explain why 5x5 was selected.

2024-10-06 21:43 UTC, jserv commented on src/draw.c
> +}
A warning raised by Clang:
```
src/draw.c:735:1: warning: non-void function does not return a value [-Wreturn-type]
  735 | }
      | ^
```

2024-10-06 22:13 UTC, weihsinyeh commented
> * [ ]  The original
> 
> <img alt="the original" width="640" src="https://private-user-images.githubusercontent.com/478921/373981144-c3faba5d-1cc4-4909-af3d-eac3d1b95b97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyNTMwMjAsIm5iZiI6MTcyODI1MjcyMCwicGF0aCI6Ii80Nzg5MjEvMzczOTgxMTQ0LWMzZmFiYTVkLTFjYzQtNDkwOS1hZjNkLWVhYzNkMWI5NWI5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNlQyMjEyMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMTliODcxZWZkODM1OTAxNGI2Yjk1YzI4Zjg2N2RiOWNlNGY3YzU1ZTg3OThlZWQ5YmFhZWNiYjc3MDcyZWM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.eLvGGe5tPLL0QNg37oBSLVT_jjn4jMNhaufagsVyOCk">
> * [ ]  The proposed change
> 
> <img alt="the proposed change" width="640" src="https://private-user-images.githubusercontent.com/478921/373981420-76cefdfd-c29e-42f5-ba58-699af9c50518.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyNTMwMjAsIm5iZiI6MTcyODI1MjcyMCwicGF0aCI6Ii80Nzg5MjEvMzczOTgxNDIwLTc2Y2VmZGZkLWMyOWUtNDJmNS1iYTU4LTY5OWFmOWM1MDUxOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNlQyMjEyMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZTNhMDhmOTYwYzg2M2E4NjAwMzk4MzUzMWZiYjk1MmUwNGY1NmY2MjlhNDFjN2UxYjcwZTA1MTc5ZGMwNGVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.0CIPjxfZJCe2lFOuqIx3AA5n4nv4-WlBhgOQVXuNSu4">
> The idea behind Issue #34 is to implement drop shadow, one of the most popular visual effects in modern window systems and compositing window managers. The effect should be applied at the window management level, not to background images, meaning the background image should not be blurred. The graphical effect of a visually elevated shape with a shadow underneath the window frame should occur transparently.

Because I'm still unsure where to place the blur operation, whether to implement the blur in '_twin_widget_queue_paint()', as this function handles the rendering order of each widget object. It would need to read the corresponding pixel block currently on the screen during rendering to blur the current background. Or should I implement this operation when each widget's TwinEventPaint occurs?

2024-10-06 23:05 UTC, jserv commented
> Or should I implement this operation when each widget's TwinEventPaint occurs? So I first try to implement this function on the background to see its effect.

Alternatively, you can write an image viewer with drop shadow functionality to evaluate performance and visual effects in the initial stage. Once you have a better understanding of the window manager events and their flow, we can proceed with integrating it into the window system.

See [MDN: drop-shadow](https://developer.mozilla.org/en-US/docs/Web/CSS/filter-function/drop-shadow)

2024-10-06 23:07 UTC, jserv commented
> Alternatively, you can write an image viewer with drop shadow functionality to evaluate performance and visual effects in the initial stage.

For performance evaluation, you may consider the code mentioned in https://github.com/sysprog21/mado/pull/55#issuecomment-2387306609 .

2024-11-12 12:55 UTC, weihsinyeh commented
I haven't applied stack blur to the drop shadow yet, because I don't know how to access the current screen's topmost pixel map. I want to apply the stack blur to a specific region of the topmost pixel map that overlaps with the shadow and then use this as the new shadow. The topmost pixel map is efficiently updated by refreshing only the damaged areas.

2024-11-13 14:45 UTC, jserv commented
Compilation error/warning reported by Clang:
```
src/window.c:72:13: error: non-void function 'twin_window_create' should return a value [-Wreturn-type]
   72 |             return;
      |             ^
src/window.c:65:17: warning: left operand of comma operator has no effect [-Wunused-value]
   65 |         window->shadow_offset_x, window->shadow_offset_y = 50, 50;
      |         ~~~~~~  ^~~~~~~~~~~~~~~
src/window.c:65:64: warning: expression result unused [-Wunused-value]
   65 |         window->shadow_offset_x, window->shadow_offset_y = 50, 50;
      |                    
```

2024-11-13 15:26 UTC, jserv commented
I am unsure how to validate this. Could you provide the relevant procedures or methods along with the expected behavior?

2025-01-03 08:28 UTC, weihsinyeh commented
Do you want to directly reduce kernel size or use the gradient method to reduce kernel size?

2025-01-03 09:22 UTC, jserv commented
> Do you want to directly reduce kernel size or use the gradient method to reduce kernel size?

For window compositing, the blur effect should only be applied to the window decorator when creating drop shadows, not to the entire window. The kernel size shrinks.

2025-01-03 12:38 UTC, weihsinyeh commented
Do all windows need to have the drop shadow feature? And only the window on the top layer will display the drop shadow.

2025-01-04 04:09 UTC, jserv commented
It looks much better now.
<img width="504" alt="blur" src="https://github.com/user-attachments/assets/22ab7fb3-8a9c-41e7-ba14-142f3661d58a" />

The latest update enforces blur effects on the active window, matching the standard behavior of compositing window managers. To enhance the visual depth, we should replace the right and bottom window borders with drop shadows, creating darker edges that give a more dimensional appearance. This means disabling the standard border rendering on those sides and implementing drop shadow effects instead.

Reference video: [Compton Compositor](https://youtu.be/Qng0lPIat-Y?t=165)
[picom](https://github.com/yshui/picom) is a compositor for X, and a [fork of Compton](https://github.com/yshui/picom/blob/next/History.md).

2025-01-04 07:29 UTC, weihsinyeh commented
This is the version that directly applies the shadow.
![image](https://github.com/user-attachments/assets/fd605334-bce5-4183-827d-194bb2213c6b)
This is the version where the shadow has a gradient effect.
![image](https://github.com/user-attachments/assets/72400c37-8339-4aa2-9080-41e80a5a51db)
Is "Replace the right and bottom window borders with drop shadows, creating darker edges that give a more dimensional appearance" referring to one of these two?

2025-01-04 10:19 UTC, jserv commented
> Is "Replace the right and bottom window borders with drop shadows, creating darker edges that give a more dimensional appearance" referring to one of these two?

Yes, exactly.

2025-01-04 16:06 UTC, jserv commented
<img width="505" alt="drop-shadow" src="https://github.com/user-attachments/assets/64a04600-622f-4120-a46b-d3f4bdf723e0" />

The shadow should be aligned with the right and bottom borders, meaning the right shadow should be positioned at the top-right corner of the active window, while the bottom shadow should be placed at the bottom-left corner of the active window.

Action items:
* Adjust the gradient effect region to make it narrower and more visually natural.
* Make the drop shadow feature configurable via `make config`. If the feature is set, no bottom-right window decorator would appear.
* Avoid changing function prototype of `twin_window_create`, making drop shadow independent from the configurations.

2025-01-07 10:37 UTC, weihsinyeh commented
This version adds the shadow directly onto `window->pixmap` by increasing `window->pixmap->width` and `window->pixmap->height`. The previous approach involved adding an additional pixel map beneath `window->pixmap`. In the previous approach, the size of the additional pixel map was the same as `window->pixmap`.

The visual difference between this version and the previous one is that, during the blur process, it needs to be handled in the right border and bottom border. Additionally, there will be an extra gap.
![screen_2](https://github.com/user-attachments/assets/a1e384c8-e745-47e9-a2c4-b3ac2e01500e)
![screen_1](https://github.com/user-attachments/assets/b8195bbd-dcb1-4cdd-9cea-f227cd865990)

2025-01-09 04:07 UTC, jserv commented on configs/Kconfig
> +    default n
Let's enable this feature by default, allowing developers to focus on further improvements.

2025-01-09 12:07 UTC, weihsinyeh commented
The way to ensure that the drop shadow feature works with the Pixman renderer instead of the built-in one is the same as the original way. This mean these functions doesn't be affected by the setting `Renderer Selection`. Does this mean these functions should not be included in the `draw.c` file because the `draw.c` file will be replaced by the file `draw-pixman.c` ?

2025-01-09 13:28 UTC, jserv commented
> The way to ensure that the drop shadow feature works with the Pixman renderer instead of the built-in one is the same as the original way. This means these functions won't be affected by the setting `Renderer Selection`. Does this mean these functions should not be included in the `draw.c` file because the `draw.c` file will be replaced by the file `draw-pixman.c` ?

@Bennctu, can you comment this? How can we eliminate the duplicate efforts?

2025-01-09 14:16 UTC, jserv requested changes
Don't use [backtick](https://en.wikipedia.org/wiki/Backtick) characters in git commit messages for the sake of terminal compatibility.

2025-01-09 14:41 UTC, weihsinyeh commented
> > The way to ensure that the drop shadow feature works with the Pixman renderer instead of the built-in one is the same as the original way. This means these functions won't be affected by the setting `Renderer Selection`. Does this mean these functions should not be included in the `draw.c` file because the `draw.c` file will be replaced by the file `draw-pixman.c` ?
> 
> @Bennctu, can you comment this? How can we eliminate the duplicate efforts?

Integrate `draw-pixman.c` into `draw.c`. Then, use `RENDERER_PIXMAN` to set `#if` and `#endif` in the `draw.c`.

2025-01-09 19:37 UTC, jserv requested changes
Move the feature "Use different colors for active/inactive titles" to a separate git branch and create a pull request for it. This will resolve issue #86.

2025-01-09 19:50 UTC, jserv commented on src/screen.c
> +twin_pixmap_t *twin_active_pixmap(twin_screen_t *screen,
Since this function is used locally, declare it as `static`.

2025-01-11 09:35 UTC, weihsinyeh commented
The function, like `twin_composite()`, the function prototype of which is the same as the original, should be written in the following way.
```c
/* draw.c */
void twin_composite()
{
#if defined(CONFIG_RENDERER_PIXMAN)
/* implementation in draw.c */
#elif defined(CONFIG_RENDERER_BUILTIN)
/* implementation in original draw-pixman.c */
#endif
}
```
The function like `twin_argb32_to_pixman_color()`, which doesn't exist in `draw.c` can still be written in `draw_pixman.c` or be written in `draw.c` in the following way.
```c
/* draw.c */
#if defined(CONFIG_RENDERER_PIXMAN)
/* functions in draw.c */
#endif
```

2025-01-11 13:35 UTC, weihsinyeh commented
This version will use the `active_pix` and `prev_active_pix` pointers that the function `twin_active_pixmap()` find in  https://github.com/sysprog21/mado/pull/88. This aims to avoid identifying the currently/previously active pixel map twice.

2025-01-11 16:48 UTC, jserv requested changes
Rebase the latest `main` branch.

2025-01-11 18:33 UTC, weihsinyeh commented
This version adds an implementation in the function `twin_shadow_border()` to handle the case where the vertical shadow offset is larger than the horizontal shadow offset, aiming to prevent heap buffer overflow.

2025-01-12 01:43 UTC, jserv commented on include/twin.h
> +    bool shadow;
The shadow related members should be conditionally built.

2025-01-12 01:44 UTC, jserv commented on include/twin.h
> +void twin_shadow_border(twin_pixmap_t *shadow);
The stack blur functions should not appear in public header.

2025-01-12 01:45 UTC, jserv commented on include/twin_private.h
> +    })
Add macro guard. That is,
```c
#ifndef min
#define min ...
#endif
```

2025-01-12 08:05 UTC, jserv commented on apps/multi.c
> +    apps_blur(screen, x += 20, y += 20, w / 2, h / 2);
I don't think it is worthy to have an application for stack blur. Any idea to keep it?

2025-01-12 08:06 UTC, jserv commented on include/twin.h
> +void twin_cover(twin_pixmap_t *dst,
Add comments.

2025-01-12 08:26 UTC, jserv commented
<img width="205" alt="xcompmgr" src="https://github.com/user-attachments/assets/ca1d5b04-c62a-4187-93a0-12a4d94aff49" />

When using [xcompmgr](https://gitlab.freedesktop.org/xorg/app/xcompmgr) with the arguments `-c -C -f F`, I noticed it produced a common drop shadow effect rather than stack blur. I actually prefer how xcompmgr renders these drop shadows - they appear more natural and aesthetically pleasing.

2025-01-12 13:26 UTC, weihsinyeh commented on apps/multi.c
> +    apps_blur(screen, x += 20, y += 20, w / 2, h / 2);
The apps_blur() function currently only resizes tux.png. This function isn't worthwhile to show by creating a standalone window feature. If it is still not worthy to have an application by adding another function, "blur," the apps_blur() function could be removed entirely.

2025-01-12 13:30 UTC, jserv commented on apps/multi.c
> +    apps_blur(screen, x += 20, y += 20, w / 2, h / 2);
The drop shadow feature's availability depends on configuration settings, so it should not expose any public functions.

2025-01-12 13:37 UTC, jserv commented
> Additionally, there will be an extra gap.

Is it feasible to eliminate the extra gap by skipping resize icon? That is,
```diff
--- a/src/window.c
+++ b/src/window.c
@@ -274,12 +274,6 @@ static void twin_window_frame(twin_window_t *window)
         twin_matrix_translate(&m, close_x, icon_y);
         twin_matrix_scale(&m, icon_size, icon_size);
         twin_icon_draw(pixmap, TwinIconClose, m);
-
-        twin_matrix_identity(&m);
-        twin_matrix_translate(&m, resize_x, resize_y);
-        twin_matrix_scale(&m, twin_int_to_fixed(TWIN_TITLE_HEIGHT),
-                          twin_int_to_fixed(TWIN_TITLE_HEIGHT));
-        twin_icon_draw(pixmap, TwinIconResize, m);
     }
 
     twin_pixmap_clip(pixmap, window->client.left, window->client.top,
```

2025-01-12 14:33 UTC, jserv commented on include/twin.h
> +    twin_coord_t shadow_offset_y;
Make them conditionally built.

2025-01-12 14:36 UTC, weihsinyeh commented
This modification removes the original extra gap while retaining the original resized icon.

2025-01-12 14:45 UTC, jserv commented on apps/multi.c
> +                    window->client.bottom);
Error messages raised by Clang:
```
apps/multi.c:311:5: error: call to undeclared function 'twin_stack_blur'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  311 |     twin_stack_blur(window->pixmap, 5, window->client.left,
      |     ^
```

2025-01-12 15:07 UTC, weihsinyeh commented on apps/multi.c
> +                    window->client.bottom);
This error is because I move the function `twin_stack_blur()` from `twin.h` to `twin_private.h`. But I still call this function in the application. The functions called in apps will be put in `twin.h`.

2025-01-12 15:45 UTC, weihsinyeh commented on include/twin.h
> +    bool shadow;
The drop shadow functionality relies on the blur effect, but the blur effect is designed to be used independently as well. This is why in `draw.c`, the function `twin_shadow_border()` is conditionally built, while the function `twin_stack_blur()` is not.

2025-01-12 15:46 UTC, weihsinyeh commented on apps/multi.c
> +    apps_blur(screen, x += 20, y += 20, w / 2, h / 2);
The drop shadow functionality relies on the blur effect, but the blur effect is designed to be used independently as well. This is why in draw.c, the function twin_shadow_border() is conditionally built, while the function twin_stack_blur() is not.

2025-01-13 03:09 UTC, jserv commented on apps/multi.c
> +                    window->client.bottom);
> This error is because I move the function `twin_stack_blur()` from `twin.h` to `twin_private.h`. But I still call this function in the application. The functions called in apps will be put in `twin.h`.

Agree. Place it with proper comments.

2025-01-19 16:43 UTC, jserv commented
It looks much better now! However, when Pixman based rendering is used, there is no drop shadow appearing.

2025-01-20 08:34 UTC, weihsinyeh commented
I only found that there is no drop shadow appearing when Pixman based rendering is used once. However, when I try to reproduce the issuse, it render normally.
The following image is rendered by Pixman.
![Screenshot from 2025-01-20 16-30-23](https://github.com/user-attachments/assets/e0957497-b6c4-41ba-9e43-51fa8d5fbb02)
The following image is rendered by built-in way.
![Screenshot from 2025-01-20 16-32-07](https://github.com/user-attachments/assets/c04f6967-4108-43c9-aec1-ed012899840e)
The way to identify them is that image rendered by Pixman will have jagged black circle.

2025-01-20 15:31 UTC, jserv commented on apps/multi.c
> +static void apps_blur(twin_screen_t *screen, int x, int y, int w, int h)
This function should be built only if PNG support is specified.

2025-01-21 15:52 UTC, jserv commented on src/window.c
> +    window->shadow_x = 10, window->shadow_y = 10;
Furthermore, use Kconfig to specify the shadow related configurations.

2025-01-28 13:56 UTC, weihsinyeh commented on src/draw-pixman.c
> +#define twin_put_8(d, i, t) (((t) = (d) << (i)))
No. This is because these macros only be used in draw.c and draw-pixman.c now.

2025-02-01 07:30 UTC, jserv commented on src/draw-pixman.c
> +#define twin_put_8(d, i, t) (((t) = (d) << (i)))
> No. This is because these macros only be used in draw.c and draw-pixman.c now.

The macros can be placed in `twin_private.h` to reduce the code duplications.

2025-02-01 09:43 UTC, weihsinyeh commented on src/pixmap.c
> +#if defined(CONFIG_DROP_SHADOW)
This code need to be modified after #95.

2025-02-02 15:35 UTC, jserv requested changes
Rebase the latest `main` branch and resolve the conflicts.

2025-02-02 16:16 UTC, weihsinyeh commented
> The function, like `twin_composite()`, the function prototype of which is the same as the original, should be written in the following way.
> 
> ```c
> /* draw.c */
> void twin_composite()
> {
> #if defined(CONFIG_RENDERER_PIXMAN)
> /* implementation in draw.c */
> #elif defined(CONFIG_RENDERER_BUILTIN)
> /* implementation in original draw-pixman.c */
> #endif
> }
> ```
> 
> The function like `twin_argb32_to_pixman_color()`, which doesn't exist in `draw.c` can still be written in `draw_pixman.c` or be written in `draw.c` in the following way.
> 
> ```c
> /* draw.c */
> #if defined(CONFIG_RENDERER_PIXMAN)
> /* functions in draw.c */
> #endif
> ```

Is this something need to be solved first?

2025-02-02 16:24 UTC, jserv commented
> The function, like twin_composite(), the function prototype of which is the same as the original, should be written in the following way. ... Is this something need to be solved first?

The `twin_composite` function is implemented in either `src/draw.c` or `src/draw-pixman.c`, never both simultaneously. Since only one implementation is compiled and linked, there is no need to verify which renderer variant is being used at runtime.

2025-02-02 16:28 UTC, weihsinyeh commented on apps/multi.c
> +static void apps_blur(twin_screen_t *screen, int x, int y, int w, int h)
This function works with image formats such as PNG, JPG, and JPEG. I'm not sure what this means.

2025-02-02 16:34 UTC, jserv commented on apps/multi.c
> +static void apps_blur(twin_screen_t *screen, int x, int y, int w, int h)
> This function works with image formats such as PNG, JPG, and JPEG. I'm not sure what this means.

If you want to load PNG files, you have to enable PNG support in advance.

2025-02-02 16:34 UTC, weihsinyeh commented
> > The function, like twin_composite(), the function prototype of which is the same as the original, should be written in the following way. ... Is this something need to be solved first?
> 
> The `twin_composite` function is implemented in either `src/draw.c` or `src/draw-pixman.c`, never both simultaneously. Since only one implementation is compiled and linked, there is no need to verify which renderer variant is being used at runtime.

Function like twin_premultiply_alpha() and _twin_apply_alpha() and the new function like twin_cover(), twin_stack() and twin_stack_blur() are the same function in both file. Both of them would have to modify the code every time they make changes.

2025-02-03 05:49 UTC, jserv commented
> Function like twin_premultiply_alpha() and _twin_apply_alpha() and the new function like twin_cover(), twin_stack() and twin_stack_blur() are the same function in both file. Both of them would have to modify the code every time they make changes.

We can move the common routines to `src/draw-common.c` and put the dedicated implementations into `src/draw-builtin.c` and `src/draw-pixman.c` respectively.

2025-02-03 05:52 UTC, jserv commented on src/draw-pixman.c
> +            right_span++;
Rewrite as following:
```c
        } else {
            /* Calculate the range of the corner. */
            right_span++;
        }
```

2025-02-03 05:53 UTC, jserv commented on src/draw-pixman.c
> +        pt = twin_pixmap_pointer(dst, x + i, y);
Declare `pt` here.

2025-02-03 22:15 UTC, jserv commented on include/twin_private.h
> +#endif
Add gcc/clang guard. That is,
```c
# if defined(__GNUC__) || defined(__clang__)
// ... the above ...
#else /* generic implementation: potential side effects */
#define min(x,y) ((x) < (y) ? (x) : (y))
#define max(x,y) ((x) > (y) ? (x) : (y))
#endif
```

2025-02-04 05:36 UTC, weihsinyeh commented on src/draw-common.c
> +    twin_argb32_t sumInR, sumOutR, sumR, sumInG, sumOutG, sumG, sumInB, sumOutB,
```diff
-    twin_argb32_t sumInR, sumOutR, sumR, sumInG, sumOutG, sumG, sumInB, sumOutB,
```
This line cannot be deleted.

2025-02-04 05:53 UTC, weihsinyeh commented on src/draw-common.c
> +           px->width * px->height * twin_bytes_per_pixel(px->format));
The function does not exist.

2025-02-04 07:14 UTC, jserv commented on src/window.c
> +    twin_stack_blur(active_pix, CONFIG_SHADOW_BLUR, ori_wid,
Since `CONFIG_SHADOW_BLUR` is assigned via Kconfiglib with strict range, it is impossible to have unexpected values.

2025-02-04 07:20 UTC, jserv commented on apps/multi.c
> +        return;
Let's build `apps_blur` all the time even if PNG loader is absent. That is, consider the below:
```c
static void apps_blur(twin_screen_t *screen, int x, int y, int w, int h)
{
    twin_pixmap_t *raw_background = NULL;
#if defined(CONFIG_LOADER_PNG)
    raw_background = twin_pixmap_from_file(ASSET_PATH "tux.png", TWIN_ARGB32);
#endif
    if (!raw_background) /* Fallback to a default pattern */
        raw_background = twin_make_pattern();
```

2025-02-04 07:22 UTC, jserv commented on include/twin_private.h
> +#if defined(__GNUC__) || defined(__clang__)
The check of gcc/clang should be inside the `ifndef min` and `ifndef max` directives.

2025-02-04 09:18 UTC, merged

2025-02-04 09:18 UTC, jserv commented
Thank @weihsinyeh for contributing!