Fix the right bound filling incorrectly
sysprog21/mado pull request #80
Opened 2024-12-08 15:40 UTC by Bennctu

- Original:
![image](https://github.com/user-attachments/assets/c4b6a76f-d2c1-483d-9c24-5c7650f864b3)

- Modified:
![image](https://github.com/user-attachments/assets/dce35245-cc05-400a-89a1-d860d6d9d5fc)

2024-12-08 15:43 UTC, jserv requested changes
Improve the git commit message, addressing the rationale.

2024-12-09 04:09 UTC, jserv requested changes
Compose Git commit messages in the third person.

2024-12-09 06:04 UTC, weihsinyeh reviewed
If so many things are being affected, there may be other issues that haven't been identified yet. Solving this problem would eliminate the need for customization every time a drawing is made. At the same time, it's difficult to understand why only the width is incorrect, but not the height.

2024-12-09 06:15 UTC, weihsinyeh reviewed
If `window->client.right = 1` and `window->client.left = 0`, the window's client object is only allowed to access one pixel, not two. If the window's client object is allowed to access two pixels within this range, then why isn't `window->client.right` initially set to 2? That way, we could directly determine the accessible range by calculating `window->client.right - window->client.left`.

2024-12-09 06:47 UTC, huaxinliao commented
Here are my test results on the fbdev backend.

**Right-bound:**
<img src="https://github.com/user-attachments/assets/a0f5325d-0b95-45f0-81c2-6a273471cc5f" width="50%">
**Left-bound:**
<img src="https://github.com/user-attachments/assets/1012d718-7564-47b2-8768-5e2621aecfa8" width="50%">
**Upper-bound:**
<img src="https://github.com/user-attachments/assets/5c5ddd01-97fd-4a6f-8ac0-016625d7b996" width="50%">
**Lower-bound:**
<img src="https://github.com/user-attachments/assets/debcfe50-37a5-440f-90fc-56a53afc11fc" width="50%">

2024-12-15 07:24 UTC, jserv requested changes
Compose Git commit messages in the third person along with the bound checks.

2024-12-16 13:21 UTC, Bennctu commented
> If `window->client.right = 1` and `window->client.left = 0`, the window's client object is only allowed to access one pixel, not two. If the window's client object is allowed to access two pixels within this range, then why isn't `window->client.right` initially set to 2? That way, we could directly determine the accessible range by calculating `window->client.right - window->client.left`.

So, does `right` not represent the rightmost index?

2024-12-29 17:43 UTC, weihsinyeh commented
The image below is a comparison of the display screens between two commits, [8ef78ba](https://github.com/sysprog21/mado/commit/8ef78bad4adbe460edf70af3e58ad9e2af480241) and [ceb748f](https://github.com/sysprog21/mado/tree/ceb748f9a69b40c98a328361ab2f752b9e1031fa). Commit 8ef78ba is the previous commit to commit ceb748f.
![commit_compare (1)](https://github.com/user-attachments/assets/f68e6514-3d9a-4a94-b43c-608f883e9c2e)
The issue with the display not showing the rightmost pixel of the icon and clock is caused by commit [ceb748f](https://github.com/sysprog21/mado/tree/ceb748f9a69b40c98a328361ab2f752b9e1031fa).
Therefore, in [ceb748f](https://github.com/sysprog21/mado/tree/ceb748f9a69b40c98a328361ab2f752b9e1031fa), solving the heap-buffer-overflow issue by using `width - 1` is incorrect.
The heap-buffer-overflow issue can be solved by 
```c
--- a/src/poly.c
+++ b/src/poly.c
@@ -213,7 +213,7 @@ static void _span_fill(twin_pixmap_t *pixmap,
     }
 
     /* last pixel */
-    if (right & TWIN_POLY_MASK) {
+    if (right & TWIN_POLY_MASK && x != right) {
         w = 0;
         col = 0;
         while (x < right) {
```

2024-12-30 14:53 UTC, Bennctu commented
> The image below is a comparison of the display screens between two commits, [8ef78ba](https://github.com/sysprog21/mado/commit/8ef78bad4adbe460edf70af3e58ad9e2af480241) and [ceb748f](https://github.com/sysprog21/mado/tree/ceb748f9a69b40c98a328361ab2f752b9e1031fa). Commit [8ef78ba](https://github.com/sysprog21/mado/commit/8ef78bad4adbe460edf70af3e58ad9e2af480241) is the previous commit to commit [ceb748f](https://github.com/sysprog21/mado/commit/ceb748f9a69b40c98a328361ab2f752b9e1031fa). ![commit_compare (1)](https://private-user-images.githubusercontent.com/90430653/399177122-f68e6514-3d9a-4a94-b43c-608f883e9c2e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1NjY1MzYsIm5iZiI6MTczNTU2NjIzNiwicGF0aCI6Ii85MDQzMDY1My8zOTkxNzcxMjItZjY4ZTY1MTQtM2Q5YS00YTk0LWI0M2MtNjA4Zjg4M2U5YzJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMwVDEzNDM1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxMDc4NGE5ODU5M2RmMzNhYzEzZTE4MTU5ZDhiN2M0OTNiZjk5NmZiOGJkNzJiYWJhYjA5NjE4MmQ1NzhjNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HWbYt7RZQ4UADpwMQ8-xZP-_URufJsdcghFIIrfc2zw) The issue with the display not showing the rightmost pixel of the icon and clock is caused by commit [ceb748f](https://github.com/sysprog21/mado/tree/ceb748f9a69b40c98a328361ab2f752b9e1031fa). Therefore, in [ceb748f](https://github.com/sysprog21/mado/tree/ceb748f9a69b40c98a328361ab2f752b9e1031fa), solving the heap-buffer-overflow issue by using `width - 1` is incorrect. The heap-buffer-overflow issue can be solved by
> 
> ```c
> --- a/src/poly.c
> +++ b/src/poly.c
> @@ -213,7 +213,7 @@ static void _span_fill(twin_pixmap_t *pixmap,
>      }
>  
>      /* last pixel */
> -    if (right & TWIN_POLY_MASK) {
> +    if (right & TWIN_POLY_MASK && x != right) {
>          w = 0;
>          col = 0;
>          while (x < right) {
> ```

1. Your method can also resolve heap-buffer-overflow issue and includes a right-bound filling check. The code modification is concise.
2. Simply ensuring that the boundary is initialized correctly once can also resolve the above issues using my method.
![image](https://github.com/user-attachments/assets/914be067-3904-48da-872f-b52d214aaee2)

2025-01-01 09:42 UTC, jserv requested changes
The subject was not accurate. Refine it.

2025-01-01 15:05 UTC, merged

2025-01-01 15:05 UTC, jserv commented
Thank @Bennctu and @weihsinyeh for contributing!